using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Dinduction.Web.Models;

namespace Dinduction.Web.Services.Pdf.Documents
{
    public class TrainingResultDocument : IDocument
    {
        private readonly ViewRecordResultVM _model;

        // ── Color tokens ──────────────────────────────────────────────────────
        private const string ColorPrimary          = "#1A1A2E";
        private const string ColorAccent           = "#2563EB";
        private const string ColorSuccess          = "#16A34A";
        private const string ColorDanger           = "#DC2626";
        private const string ColorBgSuccess        = "#F0FDF4";
        private const string ColorBgDanger         = "#FEF2F2";
        private const string ColorBgAccent         = "#EFF6FF";
        private const string ColorTextMuted        = "#6B7280";
        private const string ColorBorder           = "#E5E7EB";
        private const string ColorSurface          = "#F9FAFB";
        private const string ColorSurfaceMid       = "#F3F4F6";
        private const string ColorSuccessBadgeBg   = "#DCFCE7";
        private const string ColorSuccessBadgeText = "#166534";
        private const string ColorDangerBadgeBg    = "#FEE2E2";
        private const string ColorDangerBadgeText  = "#991B1B";
        private const string ColorAccentBorder     = "#BFDBFE";
        private const string ColorStatusPassBorder = "#BBF7D0";
        private const string ColorStatusFailBorder = "#FECACA";

        public TrainingResultDocument(ViewRecordResultVM model) => _model = model;

        public DocumentMetadata GetMetadata() => new DocumentMetadata
        {
            Title   = $"{_model.TrainingName} - Result",
            Author  = "PT Dynacast Indonesia",
            Subject = "Training Evaluation Result"
        };

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.MarginHorizontal(2, Unit.Centimetre);
                page.MarginVertical(1.5f, Unit.Centimetre);
                page.DefaultTextStyle(x => x
                    .FontSize(10)
                    .FontFamily("Segoe UI")
                    .FontColor(ColorPrimary));

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                page.Footer().Element(ComposeFooter);
            });
        }

        // ── HEADER ────────────────────────────────────────────────────────────
        private void ComposeHeader(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().PaddingBottom(16).Row(row =>
                {
                    row.RelativeItem().Column(info =>
                    {
                        info.Item().Text("PT DYNACAST INDONESIA")
                            .Bold().FontSize(15).FontColor(ColorPrimary);
                        info.Item().PaddingTop(2)
                            .Text(_model.TrainingName ?? "-")
                            .FontSize(10).FontColor(ColorAccent);
                        info.Item().PaddingTop(1)
                            .Text(_model.EvaluationForm ?? "-")
                            .FontSize(9).FontColor(ColorTextMuted);
                    });

                    row.AutoItem().AlignRight().Column(meta =>
                    {
                        meta.Item().Row(r =>
                        {
                            r.AutoItem().PaddingRight(4).Text("Date:").FontSize(9).FontColor(ColorTextMuted);
                            r.AutoItem().Text($"{_model.FormDateRegistration:dd MMM yyyy}").FontSize(9).Bold();
                        });
                        meta.Item().PaddingTop(3).Row(r =>
                        {
                            r.AutoItem().PaddingRight(4).Text("Form No:").FontSize(9).FontColor(ColorTextMuted);
                            r.AutoItem().Text(_model.FormNumberRegistration ?? "N/A").FontSize(9).Bold();
                        });
                    });
                });

                // Divider — Height(1) agar tidak collapse
                col.Item().BorderBottom(1).BorderColor(ColorBorder).Height(1);
            });
        }

        // ── FOOTER ────────────────────────────────────────────────────────────
        private void ComposeFooter(IContainer container)
        {
            container.BorderTop(1).BorderColor(ColorBorder).PaddingTop(8)
                .Row(row =>
                {
                    row.RelativeItem().Text(txt =>
                    {
                        txt.Span("This document is automatically generated by the system and does not require a signature.")
                            .FontSize(8).FontColor(ColorTextMuted);
                    });
                    row.AutoItem().AlignRight().Text(txt =>
                    {
                        txt.Span("Page ").FontSize(8).FontColor(ColorTextMuted);
                        txt.CurrentPageNumber().FontSize(8).FontColor(ColorTextMuted);
                        txt.Span(" / ").FontSize(8).FontColor(ColorTextMuted);
                        txt.TotalPages().FontSize(8).FontColor(ColorTextMuted);
                    });
                });
        }

        // ── CONTENT ───────────────────────────────────────────────────────────
        private void ComposeContent(IContainer container)
        {
            container.Column(content =>
            {
                content.Spacing(20);
                ComposePurposeSection(content);
                ComposeProfileSection(content);
                ComposeQuestionsSection(content);
                ComposeEvaluationCriteria(content);
                ComposeResultSection(content);
            });
        }

        // ── Section title helper ──────────────────────────────────────────────
        private static void SectionTitle(ColumnDescriptor col, string title)
        {
            col.Item().PaddingBottom(8).Row(r =>
            {
                r.AutoItem().Width(3).Background(ColorAccent);
                r.AutoItem().PaddingLeft(8).Text(title).Bold().FontSize(11);
            });
        }

        // ── 1. PURPOSE ────────────────────────────────────────────────────────
        private void ComposePurposeSection(ColumnDescriptor content)
        {
            content.Item().Column(col =>
            {
                SectionTitle(col, "Tujuan Evaluasi / Training Evaluation Objective");

                col.Item()
                    .Background(ColorBgAccent)
                    .Border(1).BorderColor(ColorAccentBorder)
                    .Padding(12)
                    .Column(p =>
                    {
                        p.Item().Text(txt =>
                        {
                            txt.Span("1.  ").Bold().FontColor(ColorAccent);
                            txt.Span($"{_model.Purpose1 ?? "-"} / {_model.PurposeEnglish1 ?? "-"}").FontSize(9);
                        });
                        p.Item().PaddingTop(6).Text(txt =>
                        {
                            txt.Span("2.  ").Bold().FontColor(ColorAccent);
                            txt.Span($"{_model.Purpose2 ?? "-"} / {_model.PurposeEnglish2 ?? "-"}").FontSize(9);
                        });
                    });
            });
        }

        // ── 2. PROFILE ────────────────────────────────────────────────────────
        private void ComposeProfileSection(ColumnDescriptor content)
        {
            content.Item().Column(col =>
            {
                SectionTitle(col, "Profil Peserta / Participant Profile");

                col.Item()
                    .Border(1).BorderColor(ColorBorder)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(3);
                            c.RelativeColumn(7);
                        });

                        ProfileRow(table, "Nama / Name",                     _model.EmployeeName ?? "-",               isFirst: true);
                        ProfileRow(table, "No. Karyawan / Employee Number",   _model.UserName ?? "-");
                        ProfileRow(table, "Tanggal Training / Training Date", _model.TrainingDate.ToString("dd MMM yyyy"), isLast: true);
                    });
            });
        }

        private static void ProfileRow(TableDescriptor table, string label, string value,
            bool isFirst = false, bool isLast = false)
        {
            int topBorder = isFirst ? 0 : 1;

            table.Cell()
                .BorderTop(topBorder).BorderColor(ColorBorder)
                .Background(ColorSurface)
                .Padding(10)
                .Text(label).FontSize(9).FontColor(ColorTextMuted).Bold();

            table.Cell()
                .BorderTop(topBorder).BorderColor(ColorBorder)
                .Padding(10)
                .Text(value).FontSize(9);
        }

        // ── 3. QUESTIONS ──────────────────────────────────────────────────────
        private void ComposeQuestionsSection(ColumnDescriptor content)
        {
            content.Item().Column(col =>
            {
                SectionTitle(col, "Hasil Evaluasi / Evaluation Results");

                if (_model.QuestionAnswers?.Any() == true)
                {
                    foreach (var item in _model.QuestionAnswers)
                    {
                        bool isCorrect = item.UserAnswer == item.RightAnswer;
                        // Capture typed variable to avoid dynamic dispatch
                        var capturedItem = item;
                        col.Item().PaddingBottom(10)
                            .Element(c => ComposeQuestionCard(c, capturedItem, isCorrect));
                    }
                }
                else
                {
                    col.Item().Text("Tidak ada soal tersedia / No questions available")
                        .Italic().FontColor(ColorTextMuted);
                }
            });
        }

        private void ComposeQuestionCard(IContainer container, ViewQuestionAnswerUserVM item, bool isCorrect)
        {
            container
                .Border(1).BorderColor(ColorBorder)
                .Column(card =>
                {
                    // Card header
                    card.Item()
                        .Background(ColorSurface)
                        .BorderBottom(1).BorderColor(ColorBorder)
                        .Padding(10)
                        .Row(h =>
                        {
                            h.RelativeItem()
                                .Text($"Soal {item.Number}")
                                .Bold().FontSize(10);

                            h.AutoItem()
                                .Background(isCorrect ? ColorSuccessBadgeBg : ColorDangerBadgeBg)
                                .PaddingHorizontal(10).PaddingVertical(3)
                                .Text(isCorrect ? "Benar" : "Salah")
                                .FontSize(8).Bold()
                                .FontColor(isCorrect ? ColorSuccessBadgeText : ColorDangerBadgeText);
                        });

                    // Card body
                    card.Item().Padding(12).Column(body =>
                    {
                        body.Item().PaddingBottom(10)
                            .Text(item.QuestionTraining ?? "-")
                            .FontSize(10).LineHeight(1.5f);

                        var opts = new[] { item.OptionA, item.OptionB, item.OptionC, item.RightAnswer }
                            .Where(o => !string.IsNullOrEmpty(o))
                            .Distinct()
                            .ToList();

                        foreach (var opt in opts)
                        {
                            bool isSel = opt == item.UserAnswer;
                            bool isCor = opt == item.RightAnswer;

                            string rowBg     = Colors.Transparent;
                            string dotColor  = ColorTextMuted;
                            string textColor = ColorPrimary;
                            string labelText  = string.Empty;
                            string labelColor = ColorTextMuted;

                            if (isSel && isCor)
                            {
                                rowBg      = ColorBgSuccess;
                                dotColor   = ColorSuccess;
                                textColor  = ColorSuccess;
                                labelText  = "Jawaban Anda  \u2713";
                                labelColor = ColorSuccessBadgeText;
                            }
                            else if (isSel && !isCor)
                            {
                                rowBg      = ColorBgDanger;
                                dotColor   = ColorDanger;
                                textColor  = ColorDanger;
                                labelText  = "Jawaban Anda  \u2717";
                                labelColor = ColorDangerBadgeText;
                            }
                            else if (!isSel && isCor)
                            {
                                rowBg      = ColorBgSuccess;
                                dotColor   = ColorSuccess;
                                textColor  = ColorSuccess;
                                labelText  = "Jawaban Benar \u2713";
                                labelColor = ColorSuccessBadgeText;
                            }

                            // Capture loop variable
                            string capturedOpt   = opt;
                            string capturedRowBg = rowBg;
                            string capturedDot   = dotColor;
                            string capturedText  = textColor;
                            string capturedLabel = labelText;
                            string capturedLabelColor = labelColor;
                            bool   capturedIsSel = isSel;

                            body.Item()
                                .PaddingVertical(2)
                                .Background(capturedRowBg)
                                .PaddingHorizontal(8).PaddingVertical(6)
                                .Row(r =>
                                {
                                    r.AutoItem().PaddingRight(8)
                                        .Text(capturedIsSel ? "\u25CF" : "\u25CB")
                                        .FontSize(9).FontColor(capturedDot);

                                    r.RelativeItem()
                                        .Text(capturedOpt)
                                        .FontSize(9).FontColor(capturedText);

                                    if (!string.IsNullOrEmpty(capturedLabel))
                                    {
                                        r.AutoItem().PaddingLeft(8)
                                            .Text(capturedLabel)
                                            .FontSize(8).Bold().FontColor(capturedLabelColor);
                                    }
                                });
                        }
                    });
                });
        }

       
        private void ComposeEvaluationCriteria(ColumnDescriptor content)
        {
            content.Item().Column(col =>
            {
                SectionTitle(col, "Evaluation Criteria");

                col.Item()
                    .Border(1).BorderColor(ColorBorder)
                    .Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn();
                            c.RelativeColumn();
                            c.RelativeColumn();
                        });

                        foreach (var heading in new[] { "Evaluation Notes", "Total Score", "Remarks" })
                        {
                            table.Cell()
                                .Background(ColorSurfaceMid)
                                .BorderBottom(1).BorderColor(ColorBorder)
                                .Padding(10)
                                .Text(heading).Bold().FontSize(9).FontColor(ColorTextMuted);
                        }

                        CriteriaCell(table, new[] { "Correct = 20 points", "Wrong = 0 points" });
                        CriteriaCell(table, new[] { "0 – 60  = Unsatisfactory", "80 – 100 = Satisfactory" });
                        CriteriaCell(table, new[] { "< 80  = Failed", "≥ 80  = Passed" });
                    });
            });
        }

        private static void CriteriaCell(TableDescriptor table, string[] lines)
        {
            table.Cell().Padding(10).Column(c =>
            {
                foreach (var line in lines)
                    c.Item().Text(line).FontSize(9);
            });
        }

        // ── 5. RESULT ─────────────────────────────────────────────────────────
        private void ComposeResultSection(ColumnDescriptor content)
        {
            int    score       = _model.Score;
            bool   passed      = score >= 80;
            string statusBg     = passed ? ColorBgSuccess        : ColorBgDanger;
            string statusBorder = passed ? ColorStatusPassBorder : ColorStatusFailBorder;
            string statusColor  = passed ? ColorSuccess          : ColorDanger;
            string statusLabel  = passed ? "LULUS"               : "TIDAK LULUS";

            content.Item()
                .Border(1).BorderColor(ColorBorder)
                .Row(row =>
                {
                    // Score block
                    row.RelativeItem(1)
                        .Background(ColorBgAccent)
                        .BorderRight(1).BorderColor(ColorBorder)
                        .Padding(20)
                        .AlignCenter()
                        .Column(sc =>
                        {
                            sc.Item().AlignCenter()
                                .Text("Total Skor").FontSize(9).FontColor(ColorTextMuted);

                            sc.Item().PaddingTop(4).AlignCenter()
                                .Text(score.ToString())
                                .FontSize(32).Bold().FontColor(ColorAccent);

                            sc.Item().PaddingTop(8).AlignCenter()
                                .Background(statusBg)
                                .Border(1).BorderColor(statusBorder)
                                .PaddingHorizontal(12).PaddingVertical(4)
                                .Text(statusLabel)
                                .FontSize(9).Bold().FontColor(statusColor);
                        });

                    // Trainer block
                    row.RelativeItem(1)
                        .Padding(20)
                        .AlignCenter()
                        .Column(tr =>
                        {
                            tr.Item().AlignCenter()
                                .Text("Trainer").FontSize(9).FontColor(ColorTextMuted);

                            tr.Item().PaddingTop(4).AlignCenter()
                                .Text(_model.TrainerName ?? "-")
                                .Bold().FontSize(11);

                            // tr.Item().PaddingTop(20).AlignCenter()
                            //     .BorderTop(1).BorderColor(ColorBorder)
                            //     .PaddingTop(6)
                            //     .Text("Tanda Tangan / Signature")
                            //     .FontSize(8).FontColor(ColorTextMuted);
                        });
                });
        }
    }
}